### ISSUE TITLE
Error initializing ViGem!

### ISSUE THREAD

**Issue by squatch04** [Alia5/GloSC#11]
I'm using GloSC 1.2.1.20 64-bit I get "Error initializing ViGem!" in the command window, plus a dialog box with the same error.

It executes and works fine after I click OK on the dialog box though. Is there a fix for this?

**Comment by DawsSangio** [comment]
You have to manually update Vigem downloading the latest release from its repository, and install the library using relative .inf.

**Comment by squatch04** [comment]
That worked! Thanks for taking the time to explain it.
