### ISSUE TITLE
UWP: Cannot Find MS Flight Simulator 2020

### ISSUE THREAD

**Issue by CMDRZOD** [Alia5/GloSC#117]
I just installed GloSC hoping to get Ms Flight sim working using xinput.

Unfortunately it is not found in the UWP app list. Also I cannot seem to input the link manually. I tried new version 2.0.7 which finds more UWP apps but still does not find MS Flight Sim 2020.

**Comment by pwed** [comment]
Hi I also ran into this issue and just added it manually with the following as the Path

Microsoft.FlightSimulator_8wekyb3d8bbwe!App
![image](https://user-images.githubusercontent.com/11713379/90724203-7f64b400-e301-11ea-9200-b6b056eee464.png)


Hope this helps
