### ISSUE TITLE
"Enable virtual controllers" always creates 4 controllers

### ISSUE THREAD

**Issue by mikevb1** [Alia5/GloSC#12]
This is quite a large issue in some single-player games that take input from every connected controller. With only one Steam controller this creates 4 virtual controllers all sending the same input, so the game will take the same input 4 times.

**Comment by Alia5** [comment]
In steam, turn on ( or off, unsure )support for all third party controllers
as a temporary fix.

Michael <notifications@github.com> schrieb am So., 23. Apr. 2017, 02:33:
