### ISSUE TITLE
GloSC currently doesn't seem to work with Destiny 2

### ISSUE THREAD

**Issue by ahydronous** [Alia5/GloSC#121]
I've have
- Xbox One controller connected via Bluetooth
- GloSC 2.0.6, and accompanying VIGem installed
- Windows 10, 20H2, build 19042.685
- GloSC instance with 'enable overlay' and 'virtual controllers' ticked
- 'Launch game' ticked with the path 'C:/Program Files (x86)/Steam/steamapps/common/Destiny 2/destiny2.exe'

However, when I go to 'controller configuration' I did a silly test binding: remap right stick click to right trigger. But the game still receives right stick click and still crouches instead of firing. Something is either preventing GloSC from working properly or Destiny is actively circumventing GloSC.

**Comment by Thracky** [comment]
GloSC is meant to enable Steam controller support for non-Steam games so you can use Steam's controller configuration, or the Steam Controller itself, in a non-Steam game. Destiny 2 is a native Steam game and as such is not something you should be using GloSC for.

Destiny 2 has native xinput controller support built in, and should not need any tweaking whatsoever for use with an Xbox One controller, and I've used it myself with no issue. It also has Steam Controller support which was really quite bad last I checked, and required a lot of manual editing of the controller config file, but GloSC would not change that whatsoever.
