### ISSUE TITLE
GloSC doesn't send inputs to the game

### ISSUE THREAD

**Issue by RoVluche** [Alia5/GloSC#124]
### **Context**

- **Games:** Sonic Heroes / Need for Speed: Most Wanted
- **Config:**
![image](https://user-images.githubusercontent.com/36475176/108245187-45f5ef80-7150-11eb-9c97-7cd8a3563ea6.png)
(Settings are the same for Sonic Heroes except for the path pointing to the appropriate exe)
- **Controller:** Official Switch Pro Controller connected via usb
- **Additional Third Party programs:** [XInput Plus](https://sites.google.com/site/0dd14lab/xinput-plus) has been setup for both games to convert the XInput to DirectInput. Using [ThirteenAG's Widescreen Fix](https://github.com/ThirteenAG/WidescreenFixesPack) for both games (naturally using the version for the specific game)
- **Extra Note:** GloSC has worked properly before on both games. Nothing has been changed between GloSC working and the issue appearing.

### **Issue**
After setting up GloSC and adding the instances to steam I run the GloSC instance for the appropriate game through steam and the overlay appears. At this point my controller now emulates XInput as expected. This is confirmed by XInput Plus reacting to the inputs. Afterwards I launch the game, it goes to fullscreen. From this point, no input is going through from the controller to the game. Notably, the overlay is also hidden behind the game itself. The game seems to be taking priority over the overlay which presumably also overlaps the virtual controller from GloSC. 

I'm not sure what is going on. There probably is some setting that I set up wrong but I'd have no idea at this point what it could be.

### **Workaround**
I managed to find a workaround to the issue by setting the games to borderless windowed mode using ThirteenAG's Widescreen Fix. I added a file called wndmode.ini and using notepad typed in the file only "Border=1". This makes the game run in borderless windowed mode, keeping the overlay on top of the game. This makes the games playable for me personally but some clarification as to why GloSC doesn't take priority when a game is fullscreen would be appreciated.

**Comment by Alia5** [comment]
As it states in the FAQ, GloSC itself creates just a borderless-window.
