### ISSUE TITLE
Fullscreen with Minecraft W10 Edition half FPS

### ISSUE THREAD

**Issue by DawsSangio** [Alia5/GloSC#13]
Hi, I got a very strange behaviour:
Using latest GloSC 1.2.1.20.
Lastest ViGEM driver 1.6.1.10.
Windows 10 x64 Creator update 15063
Using GloSC with Minecraft windows 10 Edition (UWP) in fullscreen got me half of the fps (30).
Using GloSC with Minecraft W10E in window got perfectly 60fps.
Tryed with hooking or not hooking.
Tryed a desktop binding and launch Minecraft manually.
Nothing change, same behaviour.

If I launch Minecraft without GloSC (id: not SteamTarget running) it works flawless 60fsp fullscreen and windows.

I report this as I presume there's something wrong in the Steamtarget.exe.
My suspect is something not compatible from SFML and windows 10 CU 150063.

Thanks.

**Comment by Alia5** [comment]
Could not reproduce here.

May I ask how you measured FPS?

**Comment by DawsSangio** [comment]
Hi, I can't measure fps. dxtory is not able to hook Minecraft, for unknown reason, and also crush GloSC.
But is really evident using naked eyes that the fps is not the same compared from fullscreen and windowed.
Also another thing: when using GloSC in windowed mode, you get full fps, but you're unable to use the mouse: the clicks aren't working, you're only able to move the cursor. This independently from which binding you're using. Only in fullscreen the mouse works.
The keyboard still works in both mode.

**Comment by Alia5** [comment]
I checked with the latest version of dxtory and got 60fps in all cases.

Without a concrete measurement, I'd say this is invalid...

**Comment by DawsSangio** [comment]
ok, I've just test with dxtory 2.0.142, fps are exactly 30 in fullscreen and 60 in windowed mode.
I'll investigate more.

**Comment by DawsSangio** [comment]
Well, I've to add that Halo:Spartan Assault don't show the issue. Sonic dash show the issue and also Shadow Fight 2, so maybe is something relative to how this apps manage the fullscreen mode.
The most strange thing is when I run GloSC without launching any apps, I got problems on the mouse (the normal mouse not emulation) the clicks and mouse-overs are not get by normal application like Edge, only top bar screen seems to works, all go back to normal as soon I shut down Steamtarget. Clicking relative taskbar application icons wont fix.
BTW I got stable 30fps on the overlay over desktop with dxtory.

**Comment by DawsSangio** [comment]
OK, got some progress, I've a little confident in VS2015 so I've changed SteamTargetRender.h line 76:
int iRefreshRate = 30; 
to
int iRefreshRate = 60;
recompiling it give me more strange results, a rock solid 20fps in fullscreen, and same 60fps windowed.
So I guess is here the road to investigate, but my poor knowledge of C++ can't be usefull.

**Comment by DawsSangio** [comment]
I've uploaded a shot clip showing the issue:
[](https://youtu.be/VI8I-dv6EP4)
moving the mouse cursor over the top, you recall the menu bar (unfortunately not visible in the video) this put the fps up to 60. Removing the mouse cursor back to the main windows, fps drop again to 30.
PS: I've two different pc with windows 15063 showing the same issue, and a third with old 14393 without the issue.

**Comment by DawsSangio** [comment]
more test:
2 Lapotop PC  -> isssue
1 desktop -> ok
1 Tablet x86 -> ok
all with windows 15063, so it's not strictly relative to the OS, but something else.

**Comment by Alia5** [comment]
It's really strange.

I seriously don't have any idea what causes this.
Also, without being able to reproduce, investigating this will be hard - impossible on my end.

**Comment by DawsSangio** [comment]
Understand, no problem.
I'm very nitpicking here, but I guess is something related to old hardware vs new hardware in term of features supported in DX11 and/or OpenGL that cause conflicts, as:
old laptop with Optimus intel HD2000 -> problem
same laptop with GT550M -> problem
Very old laptop with GT240M -> problem
New PC with GT 970 -> ok
Tablet with Atom intel HD graphics -> ok
Nothing change using latest nvidia driver.
Also compiling using latest SMFL 2.4.2 do not change anything.

**Comment by DawsSangio** [comment]
Happy to say that with 1.3.0 this issue is fixed.
Thanks.!
