### ISSUE TITLE
Multiple inputs per button press with Gears of War 4

### ISSUE THREAD

**Issue by castrojo** [Alia5/GloSC#16]
Thanks for GloSC, I was able to enjoy a playthrough of Gears of War and it worked perfectly!

With Gears of War 4 however, it seems that each input from the steam controller is sent along as 2-3 times for each keypress. So for example, I push the stick down once and in the menu it is registered as hitting down 3 times. If I hit right bumper it registers as hitting it a few times, and so on. 

I've replicated the issue with multiple community profiles, so I don't think it's a specific profile in steam, I've also been able to replicate it on another machine with a different controller, so I'm pretty sure it's not a local issue with one machine. I'm not sure how I can put GloSC into debug mode or where it logs (if at all), but happy to attach any debugging information that might help.

**Comment by hydhyd** [comment]
Same issue with Forza Horizon 3 and Steam Controller. LB/RB/A keypresses are definitely touch and go.

Wish I could provide debug information, but not exactly sure how.

**Comment by Alia5** [comment]
As said in another Issue and in the FAQ Troubleshooting section:
"Enable Xbox360 controller rebinding in Steam!"
