### ISSUE TITLE
Requires admin to run?

### ISSUE THREAD

**Issue by daninthemix** [Alia5/GloSC#18]
GloSC isn't picking up all my UWP apps - perhaps because it demands admin, and my main account (the one with my UWP games) is a non-admin account. Also it doesn't detect Steam running, I suspect for the same reason. Is admin really necessary?

**Comment by daninthemix** [comment]
Oops, should've used the installer. I'm got a shortcut sorted, and it does launch Forza, but input from my Dual Shock 4 doesn't work at all, and I can't bring up the overlay (both of which I thought were the point of this?).

**Comment by daninthemix** [comment]
Nope, works perfect! I guess I had a previous GloSC instance in memory or something (that 'close shortcut when the game closes' is worth using).

**Comment by daninthemix** [comment]
I confused myself by shimming GLoSC so it didn't require admin, but this caused other issues. Please provide a solution so that non-admin users can run GloSC - use a service to account to load whatever drivers you need, or run resident whatever service you - and then let the main GLoSC.exe run in the user context with normal privileges, so that normal users can create shortcuts.

**Comment by Alia5** [comment]
To automagically add shortcuts to Steam, admin privileges are required. There's nothing to do about.
If you can't obtain admin privileges, you have to add them manually.

This is the correct scheme: 
```"D:\Games\GloSC\SteamTarget.exe" "./targets/Forza Horizon 3.ini"```

**Comment by daninthemix** [comment]
Adding the shortcuts still worked even when I run GLoSC non-admin (using RunAsInvoker). But the actual controller input didn't work I guess because GloSC_GameLauncher.exe also has the RunAsAdministrator flag (I guess that truly does need admin?)
