### ISSUE TITLE
GloSC 1.2.4, ViGem 1.11.1.0, "cannot find file specified"

### ISSUE THREAD

**Issue by aionys** [Alia5/GloSC#23]
Every time I try to run this I get the following error:

00007FF72D6ED820 found;  Module at: 0x00007FFB19710000
Unable to open registry for joystick at index 0: The system cannot find the file specified.
Hooking Steam...
Successfully hooked Steam!

**Comment by Alia5** [comment]
Does controller emulation work regardless?

**Comment by aionys** [comment]
No. If "Enable virtual controllers" is on, GloSC crashes. If off, no crash
but no controller.

**Comment by Alia5** [comment]
Win version?

Are you sure ViGEm is installed properly?

You can try manually re-installing that.

Check your device manager,
Under system-devices, there is a "Virtual Gamepad Emulation Bus"
If there are multiple, or one with a yellow triangle, uninstall all from there.

Afterward, open up a command line window (as admin), navigate to the directory of GloSC/redist and execute
"devcon_x64.exe install ViGEm\x64\ViGEmBus.inf root\ViGEmBus"

x86 (32bit) GloSC builds are currently dropped, btw.

**Comment by aionys** [comment]
Only one entry, no triangle, already tried uninstalling and reinstalling
all three drivers using the version directly from the vigem github.

**Comment by aionys** [comment]
And I did install the x64 version.

**Comment by Alia5** [comment]
Phew....

Again, Windows version?

You can try the latest available ViGEm version, if not already.
Also, try GloSC 1.2.2 and only use EnforceBindingDLL.dll from 1.2.4

**Comment by aionys** [comment]
Windows 10 Pro, latest updates installed.

Latest ViGEm is 1.11.1.0, directly from their github repo.
Installed GloSC by using 1.2.2 installer and replacind the dll with the 1.2.4 version.

I've already researched this problem and tried the solutions supplied without success, including everything you've suggested.

**Comment by aionys** [comment]
(Side note: Either Visual Studio or WinSDK must be installed to have the device console (devcon / devcon_x64), if not installed must use "Add Legacy Hardware -> Have Disk" from the Device Manager.)

**Comment by Alia5** [comment]
It is bundled with GloSC.
ViGEm doesn't properly install without it....

**Comment by aionys** [comment]
Oh, that devcon. Okay. I did that. It added a new line to the console output and I'm still getting a crash.

00007FF75688D870 found;  Module at: 0x00007FFB176B0000
Unable to open registry for joystick at index 0: The system cannot find the file specified.
Hooking Steam...
Successfully hooked Steam!
realXgstate: 00007FFB2D601550

**Comment by aionys** [comment]
I have tried everything I can think of, including what you suggested, short of compiling ViGEm from source, and it's still not working.

**Comment by aionys** [comment]
Yeah, still having this issue, by the way.
