### ISSUE TITLE
Instructions for installing on Windows 7?

### ISSUE THREAD

**Issue by twotone8** [Alia5/GloSC#24]
when starting a steam shortcut created with GloSC, a small cmd box opens for a split second, then nothing.   There are no controllers installed in 'devices and printers'.  Not exactly sure where to go from here.  Is Windows 7 compatibility still an issue?

**Comment by Alia5** [comment]
Currently, broken.

**Comment by Skeuos** [comment]
any ETA?

**Comment by Alia5** [comment]
Can you try out the 1.4.2 pre-release?
You minimally need windows powershell v5

**Comment by Alia5** [comment]
Can you try this https://github.com/Alia5/GloSC/releases/tag/2.0.0.117 ?
In addition to this https://github.com/Alia5/GloSC/issues/42#issuecomment-373951907

Also the necessary preps for Win7 from ViGEm:
https://github.com/ViGEm/ViGEmBus

**Comment by alidan** [comment]
will do this in around a month, a bit after this didn't work, I went to trying to use a ps3 controller, this worked, but potentially has been throwing bluescreens, I isolated everything around it and want to keep it this way for another 3 weeks to see if this was the cause, then after completely reverting with another week to make sure I got everything. 

Will gladly do this the moment the problem is dealt with.

**Comment by clst** [comment]
Works perfectly fine on Windows 7 if you manually install ViGEmBus.
Who in their right mind thought installing device drivers over the internet with Powershell was a good idea?

Here is what I did instead (no need for powershell at all):

- Go here: https://downloads.vigem.org/stable/ (This is the official site for stable binaries, linked here: https://github.com/nefarius/ViGEm )
- I grabbed: ViGEmBus_signed_Win7-10_x86_x64_v1.14.3.0.zip
- Install the correct version. I did it via: Device Manager -> Action -> Add legacy hardware -> Have Disk...
- Fire Up GloSC and enjoy

**Comment by nefarius** [comment]
I do have the tools to create the classic "next-next-finish" setup package but they unfortunately don't integrate well into the build chain and I'd rather sacrifice end-user comfort than my automation. `devcon` also does the job and you are allowed to redistribute and bundle it with your solution.
