### ISSUE TITLE
XInput randomly stops functioning

### ISSUE THREAD

**Issue by zelmon64** [Alia5/GloSC#25]
I use an AutoHotkey script to turn a joystick into a keyboard /  mouse to control my computer. I wanted to try this with the steam controller and found GloSC. Using the Desktop-Config option seemed to work reasonably well.

I switched back to using my original controller for about a week then thought I'd try the SC again but wirelessly this time and with a slightly different configuration. Now when I use GloSC the XInput functions seem to randomly stop responding. To get it working again I have to restart the GloSC "game".

There doesn't seem to be a reason why the XInput functions stop responding. It will be working fine then just stop. I've tried using the AutoHotkey script [JoystickTest](https://autohotkey.com/docs/scripts/JoystickTest.htm) to see what is happening and it appears that the XInput is freezing.

Are there any log files I can provide to help identify the problem?

**Comment by Alia5** [comment]
Is this still relevant with V1.3.0?

**Comment by zelmon64** [comment]
I haven't tried it. I reworked my script to use keys instead. I'll try it now.

**Comment by zelmon64** [comment]
The freezing was previously happening randomly but certainly within an hour. It hasn't happened to me yet with V1.3.0 so I'm satisfied to mark this as resolved.

Thanks for this update. It's so much nicer to have analogue control rather than mapping the touchpad to discrete keys!
