### ISSUE TITLE
Computer Runs Extremely Slow after installing GloSC

### ISSUE THREAD

**Issue by rmharold** [Alia5/GloSC#26]
Hi,

I installed GloSC on two different computers and both began running very slow with 100% disk usage soon after. I had to use system restore to reset one computer. The other one I had to reset the computer. Is there a virus in GloSC or do you know why it makes a computer use 100% disk usage and run really slow?

**Comment by FlipEnergy** [comment]
Are you able to see which program is using the majority of disk usage? Sounds like you're saying the disk usage spike occurs after you install but GloSC doesn't even run all the time.
