### ISSUE TITLE
Need to re-run GloSC everytime Steam restarts

### ISSUE THREAD

**Issue by squatch04** [Alia5/GloSC#27]
Everytime that Steam restarts or my system reboots, GloSC no longer launches the specified game. GloSC hooks to the Steam overlay properly but no longer launches the game.

I have to reopen GloSC and click "Add all to Steam" to get it working properly again.

I'm running Windows 10 64-bit version 1709.

**Comment by Alia5** [comment]
Did you use the installer?
Or the zipped version?

GloSC_GameLauncher.exe has to run at system startup (**as admin**).
Proper way to do that would be via windows task scheduler.

You can also execute this on commandline:
"schtasks.exe /create /f /tn "GloSC_GameLauncher" /tr "[PATH_TO]\GloSC_GameLauncher.exe" /sc onlogon /rl highest"

See: https://github.com/Alia5/GloSC/blob/master/Build_Install.md

**Comment by squatch04** [comment]
The task scheduler command is working. The game now executes with the overlay after a restart. Thank you.
