### ISSUE TITLE
GloSC launcher running in UAC Elevated mode causes Steam to force SC into Lizard mode

### ISSUE THREAD

**Issue by WombatFromHell** [Alia5/GloSC#28]
Ever since Valve reworked their UAC detection code a few weeks ago GloSC has been having trouble with Steam forcing the Steam Controller into Lizard Mode when it detects focus on the SteamTarget.exe dummy window.

I'll probably also file this as a bug with the Steam developers, but I just thought I'd let you know if you hadn't tested GloSC on the steam client beta branch yet.

**Comment by Alia5** [comment]
The issue here is that Steam cannot send the controller to lizard-mode anymore if GloSC is running?

**Comment by WombatFromHell** [comment]
I probably didn't explain it clearly, so I'll try again...

The issue is that GloSC_GameLauncher.exe is running with elevated permissions so it can launch programs and hook properly, thus any program launched from it runs under its elevated permissions which Steam gets confused by and thinks it needs to be in Lizard Mode to interact with the game window. The SteamTarget.exe dummy window works fine (Lizard Mode is disabled when interacting with it), but the actual input to the game window is disrupted by Lizard Mode so the user selected config never gets used.

**Comment by Alia5** [comment]
Just clearing up a misconception here:
GloSC_GameLauncher doesn't hook anything.
It needs (rather needed) admin privilegges to UN-hook Steam ;)

Anyway this is fixed by commit 18a51cf9c3a6b0497c78a86171d25ef2d0ce0ffc
