### ISSUE TITLE
Super Lucky's Tale is not detected or launchable

### ISSUE THREAD

**Issue by kode54** [Alia5/GloSC#29]
I cannot find the game in the UWP list, and when adding its identifier manually:

```
Microsoft.AcornUWP_1.1.2019.2_x64__8wekyb3d8bbwe
```

it won't launch either.

E: Maybe it's because the game is NTFS encrypted?

**Comment by Alia5** [comment]
"E: Maybe it's because the game is NTFS encrypted?" - Nope
Forza games are encrypted as well and work fine

Any free app this issue occurs, so I can reproduce?

**Comment by kode54** [comment]
I'll see if I can find any free games that don't show up, but it's possible it only happens for AAA titles, which are all rather expensive. I suppose if I were desperate, I could send a gift code your way just to see if this is fixable.

**Comment by Alia5** [comment]
Seems you know how to write c/c++ code

```
LaunchUWPApp(LPCWSTR packageFullName, PDWORD pdwProcessId)
{
CComPtr<IApplicationActivationManager> spAppActivationManager;
	HRESULT result = E_INVALIDARG;
	// Initialize IApplicationActivationManager
	result = CoCreateInstance(CLSID_ApplicationActivationManager, NULL, CLSCTX_LOCAL_SERVER, IID_IApplicationActivationManager, (LPVOID*)&spAppActivationManager);

	if (!SUCCEEDED(result))
		return result;

	//This call causes troubles; especially with our always in foreground overlay-window
	/*
	// This call ensures that the app is launched as the foreground window
	result = CoAllowSetForegroundWindow(spAppActivationManager, NULL);
	if (!SUCCEEDED(result))
		return result;
		*/


	CoAllowSetForegroundWindow(spAppActivationManager, NULL); //try running it regardless

	// Launch the app
	result = spAppActivationManager->ActivateApplication(packageFullName, NULL, AO_NONE, pdwProcessId);

	return result;
}
```

Experiment with this to see if you can help me out

**Comment by DawsSangio** [comment]
IIRC Shadow Fight 2 is free and do not show up in GloSC list.
https://www.microsoft.com/it-it/store/p/shadow-fight-2-for-windows/9nblggh0xdtm

**Comment by Alia5** [comment]
@kode54 "Microsoft.AcornUWP_1.1.2019.2_x64__8wekyb3d8bbwe" Isn't the correct ID to launch the game btw

It should be something along the lines of "Microsoft.AcornUWP_1.1.2019.2_x64__8wekyb3d8bbwe![SOME_MORE_STUFF_HERE]"

**Comment by Alia5** [comment]
@kode54 @DawsSangio How's this one working? (Just replace the .exe file)
[GloSC.zip](https://github.com/Alia5/GloSC/files/1476370/GloSC.zip)

**Comment by kode54** [comment]
Launches a window for just a moment, but doesn't actually manage to start the game, at least not for long?

**Comment by DawsSangio** [comment]
Yes, now it show a lot more UPW apps, also Shadow Fight 2!
Thanks

**Comment by Alia5** [comment]
Any other game this happens?

**Comment by Alia5** [comment]
@kode54 can you try this? Just replacing the files is enough.
[GloSC.zip](https://github.com/Alia5/GloSC/files/1485628/GloSC.zip)

**Comment by kode54** [comment]
It manages to launch the game, and controls it, but the preset seems to need adjustment. I need to set it to an Xbox controller preset.

Thanks for getting this working, though. I see the shortcut now excludes the app version number, as well.

**Comment by Alia5** [comment]
There are no config-presets.
You always have to setup your controller config manually.
