### ISSUE TITLE
Attempting to get this to work with Destiny 2. 

### ISSUE THREAD

**Issue by Dasnap** [Alia5/GloSC#30]
Any advice on getting this to work with Battlenet games? I think it gets stuck thinking that Battlenet itself is the game I'm playing when I launch 'Destiny 2 Launcher.exe'.

**Comment by Alia5** [comment]
Battle.net.exe with battlenet://DST2 as arguments

**Comment by AlexWayfer** [comment]
> Battle.net.exe with battlenet://DST2 as arguments

Doesn't work for me now. 😞
