### ISSUE TITLE
GloSC not working for AC Origins

### ISSUE THREAD

**Issue by YogaPretzel** [Alia5/GloSC#32]
#Hey Peter,

thanks for you work, it enabled me to play Dragon Age with my Steam controller through Origin.
Now I just bought AC Origins outside Steam but can not get GloSC to work with it. That is: Only when I do a fresh install I get the game going one time (with controller hints). When I start the game again I get a error message that only flickers for half a second. I think it says something about no steam target?
I have to thoroughly erase GloSC (with Revo uninstaller) and than again install it to get it working again one time. It's a pain in the ass as you can imagine. Could you tell me how to overcome this issue?
Thanks,
Ashish from The Netherlands.
(Windows 10, i5, AMD RX480 8GB)

**Comment by Alia5** [comment]
Screenshot me that error message.

Also, have you tried not launching anything from your AC Origins shortcut and launching it manually afterwards?

**Comment by YogaPretzel** [comment]
Hey Peter,

thanks for your swift reply.
It took some effort but here it is:
![naamloos 9](https://user-images.githubusercontent.com/34005259/33241863-fb9fc97c-d2cb-11e7-9e6f-cd0b7fb226ee.jpg)

Right now I get the game to work but I don't get controller hints....

**Comment by YogaPretzel** [comment]
Before I couldn't get the game to start through the direct path to the .exe file.
I had to go through the Uplay .exe file and then start AC Origins.
I just reinstalled Uplay...so a slight improvement but not the way you intented your software to work.
Thanks for your help!

**Comment by YogaPretzel** [comment]
Not launching anything from AC shortcut:
Do you mean disabling 'start game' option in GloSC?
How do a manually launch it afterwards? I think I don't understand your suggestion...sorry

**Comment by Alia5** [comment]
That's no error message. Don't worry about it.

Yes, disabling start game from GloSC and then launching AC Origins from UPlay, from explorer. Like you would do without Steam / GloSC / whatever.

However, from what it seems, this is not a GloSC issue then, but rather a problem with the game itself.
Sorry

**Comment by YogaPretzel** [comment]
Hey Peter,

ok..I'll try that. I hope I get it working. I have this work thing the coming days but I'll try it Friday.
Anyway: Thanks again for taking the time to look in to it.

Grtz Ashish

**Comment by CrispinAwesome** [comment]
Hi There!

I am having a very similar issue. I have tried just loading the GloSC app from steam but still get the below error message.  I can create another thread or provide anything else you might need.

Thank you!

![image](https://user-images.githubusercontent.com/34147597/33464701-acad226c-d611-11e7-8882-655412bd76f3.png)

![image](https://user-images.githubusercontent.com/34147597/33464713-bf725e1c-d611-11e7-86d8-10fe1de48517.png)

**Comment by YogaPretzel** [comment]
Hey Peter,
you wrote:
'Yes, disabling start game from GloSC and then launching AC Origins from UPlay, from explorer.'
What do you mean by explorer? The Microsoft browser? Because non-steam games don't show up in the online steam library.
Thanks,
Ashish

**Comment by Alia5** [comment]
"Windows Explorer" is the program that renders the taskbar / startmenu and many other shit as well as the file-browser on windows... -.-

**Comment by YogaPretzel** [comment]
Hey Peter,
just to inform you:
I think I resolved my issue, I used a community config for SC, when I changed to the standard gamepad template AC Origins recognized the controller. Somehow there's a difference between the two. Probably because the custom config was created with an in-steam copy of the game. Thanks once again for helping me out.
