### ISSUE TITLE
Using X360CE / generic controllers with Glosc

### ISSUE THREAD

**Issue by sorsorak** [Alia5/GloSC#35]
Hi and thanks for the great project. I have some issues with the project, though. First of all, I am using a generic controller with steam using the generic settings on steam. This results in four controllers and I know that disabling the generic support would solve that but it means that the generic controller will not work. When I start the game of choice using the Glosc shortcut, steamtarget.exe crashes. Though, the controller continues working after the crash within the game. 

I also tried using the VDX (X360CE support for ViGEm), this also results in the crash of steamtarget.exe. Though, the controller will not work. I have tried both the PS4 and Xbox360 options on VDX. I tested the VDX solution (with my generic controller) for a game that supports PS4/Xbox360 controllers and it showed both controllers based on the option I selected each time.

I wonder if you can add support to VDX if it is not too much to ask. That would be really great for the project and it will support every controller out there since it is based on X360CE, without having to select the generic option. 

I am using Windows 7 x64 and using VDX the controller shows as both PS4 and Xbox360 controllers depending on the option selected. Regards and thanks.

P.S. I am willing to do any tests that you require or any debugging if needed.

**Comment by Alia5** [comment]
generic controllers already work perfectly fine. 
Just enable XBOX Controller rebinding support and GloSC will not create four controllers anymore...

No need for any other shit like X360CE or VDX...

**Comment by sorsorak** [comment]
Yeah, I have tried with and without the XBOX Controller rebinding support. steamtarget.exe crashes.

**Comment by Alia5** [comment]
Something else must be wrong then

**Comment by sorsorak** [comment]
Thanks for the response, what do I need to provide, exactly? I am using the Sony PS2 original controller using the PS2 to USB Adapter. The controller appears on my PC as Twin USB Joystick. It works with X360CE perfectly without issues with all the games supporting it. ViGem/VDX work with the games that support X360CE, too. Also, I can see the controller detected as Xbox or Playstation (by looking at controller settings ingame) depending on my VDX choice.

**Comment by sorsorak** [comment]
@Alia5 
This is the error information that I got from the Event Viewer:

Faulting application name: SteamTarget.exe, version: 1.4.0.0, time stamp: 0x5a456e4c
Faulting module name: SteamTarget.exe, version: 1.4.0.0, time stamp: 0x5a456e4c
Exception code: 0xc0000005
Fault offset: 0x0000000000001672
Faulting process id: 0x1a1c
Faulting application start time: 0x01d38fbd4e3fbace
Faulting application path: C:\Program Files\GloSC\SteamTarget.exe
Faulting module path: C:\Program Files\GloSC\SteamTarget.exe
Report Id: 8d006172-fbb0-11e7-9262-047d7b667a65

I am using the latest version of Glosc. I have both Generic Support and XBox Support enabled on Steam. I hear the USB device connected sound when I start the game then I get the crash above. Some of the buttons on the controller work even after the crash.

If I uncheck the Generic Support on Steam and keep Xbox Support only, I do not hear the USB plugging sound, also no buttons work on the controller.

If there is anything you need me to do to find the bug, please let me know.

**Comment by Alia5** [comment]
Can you try this https://github.com/Alia5/GloSC/releases/tag/2.0.0.117 ?
