### ISSUE TITLE
Dependence on Steam

### ISSUE THREAD

**Issue by uppps** [Alia5/GloSC#37]
Now your tool simply allows to use Steam overlay for games that don't work well with Steam. Wouldn't be better to develop a real driver, without the dependence on Steam. I know this one for Linux:
https://github.com/kozec/sc-controller
Unfortunately it does not work (yet) in Windows. The author wants to port it, but he don't know how things work in Windows. Maybe with your experience using ViGEm you can help with the port.

**Comment by Alia5** [comment]
I do get this question a lot and I am sorry to disappoint but no.

No plans on doing that as I really don't like to rewrite all of Steams fancy mapping options.
Additionally, I think the Controller-Overlay for touch menus and shit is pretty darn awesome, also really don't want to rewrite that myself.
