### ISSUE TITLE
Crash after controller disconnect

### ISSUE THREAD

**Issue by Overload86** [Alia5/GloSC#38]
Edit: After more testing can now confirm several more bits (edits in bold)

When using GloSC with my PS4 DualShock controller, I noticed that leaving the controller alone until it disconnects also crashes the GloSC overlay. (Basic Windows "Program not responding" dialog) It doesn't always crash when disconnecting the controller manually, ~~but I am pretty sure that happened a few times too.~~ **It definitely also happens when disconnecting the controller manually** Unfortunately I cannot test it with another bluetooth controller, since I do not own any others. Doesn't matter if GloSC is itself starting another app or not btw.

Version is 1.4.1
Windows 10 64-bit (**latest updates**)
Latest Steam (**non-beta as well as beta**)

**Comment by Alia5** [comment]
Don't own a DS4, so it's kinda hard to check :/

**Comment by Alia5** [comment]
Can you try this https://github.com/Alia5/GloSC/releases/tag/2.0.0.117 ?

**Comment by JelledFro** [comment]
This also happens with my xbox controllers I think. When playing UWP games over steam link, if the controller disconnectes I have to restart the game for it to receive input again.
