### ISSUE TITLE
Error Initializing ViGem

### ISSUE THREAD

**Issue by nwpappas** [Alia5/GloSC#42]
Installing with the latest installer, I get a "Error initializing ViGem!" error when trying to run an overlay. 

On closing, the screen goes white or black (sometimes one, someone's the other). I can bring up the onscreen keyboard, and move the mouse around, but am blind as to what's going on behind.

**Comment by Kiviran** [comment]
I have the exact same issue.

**Comment by kazoooka** [comment]
#metoo

**Comment by sfabris** [comment]
#metoo Same here.

**Comment by benchesh** [comment]
Same here. Fortnite isn't getting any of my controller input and the glosc_overlaywindow seems to never close even when I quit the game and the epic launcher

**Comment by Alia5** [comment]
If you have multiple (_or none_) "Virtual Gamepad Emulation Bus" devices in your device manager (under System Devices)
Remove them and then run [this](https://github.com/Alia5/GloSC/blob/v2/redist/Install_Update_ViGEm.ps1 ) script via PowerShell.

![2018-03-17_2150](https://user-images.githubusercontent.com/3527662/37559872-cc89beae-2a2d-11e8-812d-deadf544a933.gif)

**Comment by nwpappas** [comment]
I checked and only had 1 entry. With nothing to lose, I uninstalled and ran script per instructions above, but it didn't fix the problem. I uninstalled and reinstalled (something I'd tried before) and this time it appears to work. On my desktop.

I tried it over the Steam Link and I still get the white screen. No error, but the screen goes opaque when a shotcut is run.

Is the support, or official non-support, for the Steam Link?

**Comment by Alia5** [comment]
Last time I checked, GloSC worked just fine using Steam InHome-Streaming, and therefore with the Steam Link.
However, *if* the GloSC overlay window is in focus, **or** the focused window runs in _exclusive fullscreen_ you won't see anything.

**Comment by AmazingMrBrock** [comment]
Hello, been trying is use GloSC but havent been able to yet. I've installed uninstalled installed repeatedly (as admin) and am still getting the vigem error. I have no virtual gamepads in device manager at all, that being the case I ran the vigem updater and rebooted. No dice, full uninstall reboot install reboot install vigem reboot, add game to steam (sea of thieves) reboot, try to start game, vigem error.

It seems like vigem just isn't installing on my system or something.

system is fully updated win 10 x64, steam is up to date but no beta. Glosc is v 2.0.0

**Comment by Alia5** [comment]
@AmazingMrBrock 
You could try installing ViGEm manually (without the script)

https://github.com/nefarius/ViGEm/wiki/Driver-Installation

However, be aware that "Get-ViGEmBusDevice | Remove-ViGEmBusDevice" is currently bugged if you have more than 1 ViGEm device installed. So you have to remove them manually as described above.

**Comment by AlexanderGalen** [comment]
@Alia5 
I just want to confirm that I was in the same situation as @AmazingMrBrock, and following the wiki to install ViGEm and then reinstalling GloSC fresh to undo all the other stuff I tried finally got this working for me. Thanks for the help, and thanks for making this in the first place.

If I had to guess why running "Install_Update_ViGEm.ps" didn't work, I'd wager that it's because some of the commands from the ViGEm wiki require administrator privilege, so need to be run from an administrator instance of powershell. When I tried running the script I saw the powershell window pop up and disappear immediately, so I think it may not have privileges and be silently failing. Just some speculation though, I'm no expert.

**Comment by Alia5** [comment]
The script should restart itself with admin privileges.

**Comment by heckelson** [comment]
Hi, for me (**Windows 8**) installing ViGEm manually from this [link](https://github.com/nefarius/ViGEm/releases) via _device manager > add legacy device_ and rebooting did the trick, the powershell script didn't work for me after running powershell with admin privileges and setting the _ExecutionPolicy_ to _Bypass_. I installed GloSC via the provided installer and it seems to be working now.

**Comment by AmazingMrBrock** [comment]
That did the trick for me, thanks for the help @Alia5. I also second @AlexanderGalen in thinking its an problem with automated admin privileges not transferring.

**Comment by FlipEnergy** [comment]
Windows 10 here and just installed GloSC 2.0.1.124 and installation went through successfully. However, I looked at your comment above and noticed the virtual GamePad Emulation bus wasn't installed by the script. I tried to manually run it and after it asked for admin privileges, it continues to silently fail and exit immediately. So I ended up just running powershell as admin, copy-pasting the second half portion of the script and ran/installed manually successfully and solved the Error. This is just FYI.

**Comment by Alia5** [comment]
That's interesting! 
Thanks!

**Comment by freewizard** [comment]
Same issue as @FlipEnergy . Worked around by executing
 `Set-ExecutionPolicy -ExecutionPolicy  Unrestricted`
In Windows PowerShell as Administrator

**Comment by Alia5** [comment]
I'll have it fixed in the next update then.

Thanks all.
Didn't even know that policy "crap" existed >.<

**Comment by Alia5** [comment]
https://github.com/Alia5/GloSC/commit/5d00d5c45cf391d3f1acb766877e9f7c9cb177aa

**Comment by x8009** [comment]
I have issue with  

 .\Install_Update_ViGEm.ps1
Register-PSRepository : The term 'Register-PSRepository' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Program Files (x86)\GloSc\redist\Install_Update_ViGEm.ps1:12 char:5
+     Register-PSRepository -Name nuget.vigem.org -SourceLocation https ...
+     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Register-PSRepository:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Install-Module : The term 'Install-Module' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Program Files (x86)\GloSc\redist\Install_Update_ViGEm.ps1:13 char:5
+     Install-Module ViGEmManagementModule -Repository nuget.vigem.org

And it keeps going with all the  other commands.

I am using Windows 10 1809 .

I don't know show to fix this

**Comment by Alia5** [comment]
Ah, well...
I think ViGEm stopped being available for install via Powershell... I'd have to check that, though.
There will be a plain old setup.exe for ViGEm soon and I'll update GloSC when that drops.

In the meantime, you can try the ["Caveman Instructions"](https://docs.vigem.org/#!vigem-bus-driver-installation-caveman-edition.md) (I didn't name them :P)

**Comment by x8009** [comment]
I've found the issue for me.

for some reason I didn't have files in the powershell modules folder. it's in programs files\windows powershell  .  but x86 power shell worked but not with the install because it always opened the x64. so I copied all the files from my laptop powershell x64 and it worked fine.

**Comment by nefarius** [comment]
[May I alert you fine gentlemen towards the latest and greatest news](https://github.com/ViGEm/ViGEmBus/releases/latest) 😁

**Comment by x8009** [comment]
> [May I alert you fine gentlemen towards the latest and greatest news](https://github.com/ViGEm/ViGEmBus/releases/latest) 😁

nice

We just install above / upgrade or we need to uninstall ?

**Comment by nefarius** [comment]
@x8009 just run it and let it do the work 😄

**Comment by nefarius** [comment]
[I've compiled a checklist with details on how to verify if everything worked](https://forums.vigem.org/topic/287/vigem-bus-driver-setup-test-checklist).

**Comment by minidarknova** [comment]
Issue still exist, using latest version of Windows 1903, using latest available release of GloSC. Starting ReCore a microsoft UWP game results in getting this error. Please help.  
I don't even see that Virtual Gamepad Emulation Bus in my Device Manager.

**Comment by Dhop84** [comment]
same as @minidarknova

**Comment by gybandi** [comment]
> [May I alert you fine gentlemen towards the latest and greatest news](https://github.com/ViGEm/ViGEmBus/releases/latest) 😁

Thanks! This finally solved the issue for me ;)

**Comment by willstefany** [comment]
Hi, I get the error and I tried running Install_Update_ViGEm.ps but it opens and closes the powershell right away, I think its getting the is not recognized errors. I am using windows 10 and am trying to get the steam controller to work with forza horizon 4

**Comment by nefarius** [comment]
@willstefany forget the scripts, use the setup I linked.

**Comment by Alia5** [comment]
latest commits on master use the new installer.
Release: soon(tm)

**Comment by AlexWayfer** [comment]
I have this issue now and nothing helps. I've re-installed GloSC and installed a new version of ViGEmBus. I have no virtual gamepads in Device Manager:

![image](https://user-images.githubusercontent.com/6510020/91757191-9bf0ce00-ebd6-11ea-8bee-fc78f77efe0f.png)

**Comment by pawel54321** [comment]
I found file, but I can't open (I tried admin):

.\buildViGEmClient.ps1 : File C:\Users\P\Downloads\GlosSI-0.1.2.0\GlosSI-0.1.2.0\buildViGEmClient.ps1 cannot be loa
ded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go
.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\buildViGEmClient.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by cuilean** [comment]
> I have this issue now and nothing helps. I've re-installed GloSC and installed a new version of ViGEmBus. I have no virtual gamepads in Device Manager:
> 
> ![image](https://user-images.githubusercontent.com/6510020/91757191-9bf0ce00-ebd6-11ea-8bee-fc78f77efe0f.png)
> 
> UPD: Resolved by uninstalling and installing a new version of ViGEm, instead of "repair".

many thanks bro this method worked
