### ISSUE TITLE
Issues with configs

### ISSUE THREAD

**Issue by scarrken** [Alia5/GloSC#44]
While it works fine as I first launch it, if i set it to launch an application (in this case, battle.net) it switches to a default config. Setting GloSC to open nothing and then opening the application doesn't fix the issue.

**Comment by Alia5** [comment]
You mean the controller is switching back to desktop-config?

I just checked with latest Steam-Beta, it still works perfectly fine for me...

You have to configure your individual shortcuts controller config **in Steam**

**Comment by scarrken** [comment]
No, I mean it switches to a keyboard+mouse config when I have set it up as a kb+m and controller config. It no longer falls back to a default config, but the controller part of the config doesn't work, forcing me to use a solely kb&m config

**Comment by Alia5** [comment]
Can you try this https://github.com/Alia5/GloSC/releases/tag/2.0.0.117 ?

**Comment by scarrken** [comment]
Sorry for the _very_ late response, I had just given up on the problem by using another program, but now that program doesn't work...

I tried that version of GloSC, didn't help
Tried setting steam to run as admin, didn't help either
