### ISSUE TITLE
Settings not applied

### ISSUE THREAD

**Issue by rprieto5** [Alia5/GloSC#45]
Hi everyone,

When I try to play fortnite with glosc, initially my settings work fine with the games launcher, but once fortnite launches, my controller goes back to some random settings which I cannot change (I can still use some buttons but cannot remap or anything). They are not the desktop settings.
Also, the overlay is quite faded and when i press alt+tab to focus on glosc, sound goes away.

Initially I had issues with Vigem but have since installed vigem via powershell.

I am running win 10 x64 with an nvidia gpu and amd cpu.

**Comment by Alia5** [comment]
Does it switch to desktop config, or lizard mode?

Can you try running steam as admin?

**Comment by rprieto5** [comment]
OMG it worked! After hours of searching, the solution turned out to be running steam as admin...

I am unsure what lizard mode actually means other than basic mouse and keyboard input but it was definitely not the desktop config I chose (maybe the default desktop config? i dont know whether glosc is aware of changes to the default desktop config).

The layout is still super faded and bright though (not really a game-breaking issue).

**Comment by rprieto5** [comment]
Ok nevermind, it does let me move around and do some stuff but I can still not change the bindings. For some reason the whole D-pad translates to middle click.
At least I don't have haptic feedback anymore which means it did register some of my configs, i just dont know which one.

**Comment by Alia5** [comment]
Lizard Mode is (you could say) a special set of bindings, _hard wired_ in the Controller.
Lizard Mode applies whenever Steam is not running or when any program currently focused runs with higher privileges than Steam.

GloSC enforces the first config (that is not desktop or steamchords) that comes up, when launching a shortcut. This is **always** and *only** the config of the shortcut you selected.

It does this via injecting a simple .dll file into Steam itself.

**If** you're definitely not in desktop-bindings, then I would strongly guess there is something wrong on your end.

**If** the controller switches to Lizard-Mode, its privilege issues or something I'm not yet aware of.


Might I also suggest that you try a build from the (very work in progress) v2-branch
https://github.com/Alia5/GloSC/files/1822895/GloSC-installer.zip

**Comment by rprieto5** [comment]
Ok then yes, I am fairly certain it was lizard mode.
I am doing some testing and the behavior is just plain odd. If I close steam and connect the SC, the controller has the desktop config while using chrome, spotify, file explorer, etc... yet when i open the task manager, it switches to lizard mode just like it did once fortnite launched from the launcher.

I am unsure what could be wrong with my setup. I have recently formatted my pc plus all drivers are functional and up to date. Are you thinking there is a config issue or a driver/hardware issue?

Do different apps (such as Fortnite or task manager) have different permissions than the rest?

Still however, the question remains as to why now that i launched steam as admin I have a different config yet not the one i created?

I will test v2 soon...

**Comment by rprieto5** [comment]
Ok, so far it seems v2 works. I will continue testing.

I have so far successfully reconfigured the controller (even after launching GloSC) and am able to play as expected.

Persistent issues:
Super bright/dim overlay
Vigem initialization issue (does not seem to affect though)

**Comment by Alia5** [comment]
Those mentioned are different issues.
As v2 has seemingly fixed it, I'll close this
