### ISSUE TITLE
Not applying configurations at all

### ISSUE THREAD

**Issue by Reyeselda95** [Alia5/GloSC#46]
The problem i have is the following:
After all the installation of the stable version i create my shortcut, configure my controller and everything seems to be ok.
Then i go to steam to open the app, it opens the overlay layer as it should, it opens the game as it should and i can see how the bindings are not working at all.
I can actually see it because the steam controller led changes to full power, when i have it configured to be at 10% light only to know the controller is on.
The problem is that the game, in this case is called "In Verbis Virtus" doesn't seem to detect the overlay or don't want to. When i change the window with ALT+TAB i can see the light change so i want to ask if this can be a problem of the program itself or just that it will never work for this game. I tried with World Of Final Fantasy and it didn't worked either, as the focus is not on the overlay but in the game one...thanks

**Comment by Alia5** [comment]
Does it switch to desktop config, or lizard mode?

Can you try running steam as admin?

**Comment by Reyeselda95** [comment]
Ok, yes it was the admin thingie. My bad. This is a duplicate, you can erase this as you please. The thing is that i actually readed the issue you mentioned but didn't understood it propperly.  Thanks for all your work ^^
