### ISSUE TITLE
not exactly an issue, just need some help with forza

### ISSUE THREAD

**Issue by naskosn** [Alia5/GloSC#48]
First of all, you can delete this thread whenever you want (i just couldn't find a forum about GLOSC)

So, I cant find anywhere how to run Forza Motorport 6: Apex (UWP game) with the Steam controller. Many videos i've watched, tried GLOSC aswell but nothing seemed to work. The game is opening and just cant read any of the new controls i've set to the steam controller. 

Also everytime this error appeared: "Error initializing ViGem"... so i've read the previous topic about the errot and i couldn't understand a shit. Furthermore i saw that when i close the game, the GLOSC overlay was left open and unable to close - the only way to close was via task manager where when i clicked on the task it immediately crashed.

I would be really glad if you make a simple guide on how EXACTLY i should customize Glosc and steam controller to work with forza games 

PS: Even "gladder" if you make it work with gyro for the steering like for example in project cars

**Comment by Alia5** [comment]
Your issue is exactly that
https://github.com/Alia5/GloSC/issues/42

Look there, continue asking your questions there.
Thanks.

BTW:
Gyro steering already works ;) you just have to configure the controller like you'd normally do
