### ISSUE TITLE
Unable to Resize Window

### ISSUE THREAD

**Issue by fwclements** [Alia5/GloSC#49]
After launching the application, the window remains very small and appears to have the resize disabled.  My TV settings are native 4k with 300% scaling.  I've tried bumping the scaling down to 100% but I'm unable to resize the window and therefore unable to see the entire right side of the settings screen.

Windows 10, fresh install, latest updates.

Is there any way to unlock the resize option?

![Window Screenshot](https://user-images.githubusercontent.com/1187203/38455082-89820012-3a40-11e8-8f29-34fbc304ec34.PNG)

**Comment by nappy12488** [comment]
Fixed. Go to the glosc.exe in the folder where it was installed. right click>properties>compatibility mode>Check "disable high DPI scaling behavior" Scaling preformed by "system" or "system enhanced" in drop down.
