### ISSUE TITLE
Switch Pro Controller not working with Fornite?

### ISSUE THREAD

**Issue by klassi** [Alia5/GloSC#54]
Update again: removed my Nvidia card as the default from the global settings and made it automatically select instead (as stated on the homepage of your website) and that solved the issue. Sorry for the long thread, but this can be ignored!
____________________________________________________________________

Update, found a workaround loading a Xbox Controller shortcut through steam ([as in the instructional video](https://youtu.be/YAbOiol-2B8)) but the overlay is an entirely black and I can't see anything on the screen. I edited the "bEnableOverlayOnlyConfig=1" from 0 and my Nvidia mobile card is set as the default card for all of my games but am still having issues. My Xbox Controller ini has "bEnableOverlay=1" if that is important. Any help with this issue?

______________________________________________________________________
These are the settings I'm using for Fortnite: 
[X] Enable Overlay
[X] Enable Virtual Controllers
[] Use Desktop Config
[X] Launch Game: C:\Program Files\Epic Games\Fortnite\FortniteGame\Binaries\Win64\FortniteClient-Win64-Shipping.exe
[] Close shortcut when launched Application closes (Disable for Uplay-games!)

However, whenever I launch the game via Big Picture Mode on Steam, two things happen. First, the sound of a USB plugging in and then out plays, and steam launches with my mouse cursor present, and my Switch Pro Controller does not register. 

My Switch Pro Controller works perfectly with Steam games and is configured for the shortcut created by GloSC.

Any help is appreciated, thank you!

**Comment by Alia5** [comment]
GloSC is primarily focused on Valves Steam Controller.
Other controllers may or may not work as expected, but they are *not* supported by GloSC
