### ISSUE TITLE
How do we change binds?

### ISSUE THREAD

**Issue by joe7dust** [Alia5/GloSC#56]
I was able to see what the "virtual 360" is sending by game controller settings in devices, but it looks like the grips underneath are sending the exact same signal as X and A (buttons 1 & 3). 

So how would I go about assigning the grips to shift up / down, while also being able to use the X and A buttons independently?

Additionally, it looks as though some buttons are not bound at all:

Full Trigger Pull (both Left and Right!)
Right pad center press (directionals do show as hats)
Left pad directional presses (all clicks show as button 10)

Where should we been editing the rumble settings? I saw there is more than one place to do this, default setup is very very fake feeling like the rumbler has no weight to it.

**Comment by Alia5** [comment]
You have to rebind any individual GloSC-Shortcut **like _any_ other Steam Game**
GloSC just "captures" and "forwards" what any Steam game would get, to the system.
