### ISSUE TITLE
Suddenly seemingly double inputs

### ISSUE THREAD

**Issue by Proim** [Alia5/GloSC#60]
Hi,

I've been happily using GloSC for a while. I've configured it as a general Xbox Controller which I run as a non-steam game before starting game. Suddenly I'm getting seeminly double inputs. In a games menu I'm skipping through everything like crazy. I haven't changed anything so no idea what's going on...

I already tried this from the faq, but didn't help.
Q: GloSC always creates four controllers, resulting in doubled inputs
A: Enable Xbox360 controller rebinding in Steam! It's in the "Controller" section in the Steam Settings.

**Comment by gshpychka** [comment]
Same thing. Trying to get A Way Out working.

Xbox Support is enabled. Each press generates 3-4 presses ingame. Steam is running as administrator.
