### ISSUE TITLE
Useraccount is not Admin -> UWP Apps won't show up correctly

### ISSUE THREAD

**Issue by DaStivi** [Alia5/GloSC#65]
looks like that when the user whos starting glosc is not admin the uwp apps won't show up correctly…
CloSC starts with forced admin rights via uac, thats propably fine, but then of course won't list the uwp apps that are not in the admin user profile :(

but be great to have least privilege permission, and still can use the uwp feature!
propably its somehow possible so search uwp appps for non admin users? (run glosc without having the need for admin rights at all?)

**Comment by Alia5** [comment]
> run glosc without having the need for admin rights at all?
As GloSC  *needs* to modify file contents of Steams Program folder, Admin privileges are absolutely required.

Would need to look at that UWP thing. 
Since Admin privileges are required anyway, however, I call this a non-Issue
