### ISSUE TITLE
GloSC not work...

### ISSUE THREAD

**Issue by buccheriale01** [Alia5/GloSC#66]
It's the first time I've tried GloSC, since I wanted to play Forza.
Unfortunately, as soon as I click "Add all to Steam", I get this error:

> Could not detect Steam shortcuts file!
> Make sure you have at least one non-Steam shortcut for the file to be present
> Steam must be running for it to be detect

The problem that Steam effitivamente is open (even as an administrator) ...
I do not know how to solve, can you help me?

![cattura](https://user-images.githubusercontent.com/23310822/50385385-24fef480-06d5-11e9-8988-2b38726e9710.PNG)

**Comment by Alia5** [comment]
It tells you.
*Add any Game or Program as non-Steam game first.*
Then GloSC will create Steams "non-Steam game" shortcuts file.
