### ISSUE TITLE
When use GloSC with Steam Link, the screen will zoom in 4 times bigger.

### ISSUE THREAD

**Issue by s951736** [Alia5/GloSC#67]
Hello, GloSC works great when I use it on PC, but has some problem when use it with Steam Link.

When I run a game with GloSC via Steam Link, the screen will zoom in 4 times bigger, and it's just unplayable since most of things will be not in the screen.

My PC has 4k resolution and Steam Link has 1080p, when Steam Link runs a game, it always zoom in to the game window if it's not a full-screen game (Steam Link is programmed this way). 
So I guess GloSC's hidden overlay has 1080p resolution, so Steam Link zoom in to that size when GloSC is running.
Is there any solution for this? I hope I can use it with normal screen size.
Or is there some way I can force set the GloSC overlay to 4k resolution?

Thanks.

**Comment by Alia5** [comment]
Hmm, interesting.
Never had any problems streaming from my 1440p desktop to my 1080p Steam Link, or even some MacBook-Air (whateverthe... it runs)

Normally, the GloSC Window will run in your desktop resolution which, in your instance, would be 4k.
In my experience Steam Link streaming (or any sort of Steam InHome Streaming) will then just downscale that to whatever your streaming output has. 

If that's not the case you could give [Borderless Gaming ](https://github.com/Codeusa/Borderless-Gaming/releases) a chance and report how it works out for you.

Probably have to cook something up though.
No guarentess when and if this even happens anytime soon, sorry

**Comment by s951736** [comment]
After I tried Borderless Gaming and it doesn't work, I finally found the answer, it's an app called Duet Display that makes graph function on my PC not normal, it's an app makes iPad become a second monitor, it also makes directX behave strangely for my PC, what a trash app, uninstall it then everything works fine!
Thanks!
