### ISSUE TITLE
Any way to hide this from the Oculus Rift?

### ISSUE THREAD

**Issue by Kzitold** [Alia5/GloSC#73]
Wanting to use the Steam Controller to play non-VR games on a bigger screen using GloSC, but it's doing VR stuff and I can't click it in "Devices" to remove it.

**Comment by Alia5** [comment]
Nah. Oculus basically "stole" the ViGEm Driver that GloSC also uses.
More Info here: https://forums.vigem.org/topic/47/psa-oculus-software-can-crash-your-machine

**Comment by nefarius** [comment]
Nag the Oculus Support, it's their fault. And they expect the community to fix their sh*t.
