### ISSUE TITLE
Zip version produces error "The code execution cannot proceed because Qt5Network.dll was not found" 

### ISSUE THREAD

**Issue by LyraelRayne** [Alia5/GloSC#77]
Pretty sure the zip file is just missing the DLL.

**Comment by RDmvv** [comment]
after you put the ddl in the folder i get an error "entry point not found" how do i fix that?

**Comment by LyraelRayne** [comment]
I'm going to guess you downloaded a version of that file from the Internet and it was the wrong version.

At this point in time the best bet is to install it using the .exe installer on the Release page. If you really want to use the zip version, I've attached a screenshot showing which version of the DLL is installed when installing using the .exe. GitHub wouldn't let me attach the .dll :(


![image](https://user-images.githubusercontent.com/11632412/58391737-6a579180-807a-11e9-816d-82fb4c531560.png)

**Comment by RDmvv** [comment]
ok thanks

**Comment by Alia5** [comment]
Should be fixed: 047e253ba5164bbe9fcf97c39a5a6d8ab868d379
