### ISSUE TITLE
ViGEm not installing properly

### ISSUE THREAD

**Issue by stan-potapov** [Alia5/GloSC#78]
The current Install script for ViGEm is out of date, and provides this error:
Install-ViGEmBusDeviceDriver : The remote server returned an error: (404) Not Found.
At C:\Program Files (x86)\GloSC\redist\Install_Update_ViGEm.ps1:18 char:1
+ Install-ViGEmBusDeviceDriver
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo		: NotSpecified: (:) [Install-ViGEmBusDeviceDriver], WebException
    +FullyQualifiedErrorId	: System.Net.WebException.ViGEmManagementModule.Cmdlets.InstallViGEmBusDeviceDriver

I had to manually install it from their github which is currently located here https://github.com/ViGEm

While it wasn't hard once I found it, it was a pain to find. I just wanted to bring this to your attention so that other people wouldn't have to slog their way through finding it as well.

**Comment by nefarius** [comment]
[That's the full official link](https://github.com/ViGEm/ViGEmBus/releases/latest) 😛

**Comment by barbafa** [comment]
I have this issue too, and will try the workaround. 
Also, the installer for GloSC does not by itself show anything wrong when this occurs, and the powershell window closes very very fast, so no chance of being able to read it's output. 
Suggest that the GloSC installer should pick up error from PowerShell and display them to the user, or make sure that the power shell window does not close if it returns any errors.

**Comment by nefarius** [comment]
The PowerShell installation method is **dead**, it has to be removed/reworked.

**Comment by airjer** [comment]
> The PowerShell installation method is dead, it has to be removed/reworked.

Does this mean the current release isn't working? I just discovered all of this and it's giving an error that it can't find VigEm when I launch a game although I have 1.16 installed.

Thanks

**Comment by nefarius** [comment]
@airjer ViGEmBus detection should have absolutely nothing to do with how it got installed. If the device is there it will work, as simple as that.

**Comment by airjer** [comment]
What do you think my issue could be?

**Comment by nefarius** [comment]
@airjer that's way too little info to recommend anything, IDK how the application does the detection.

**Comment by Alia5** [comment]
56e4e666bf19e680544a662135af8d3aa1b2ac78 incluides latest installer
4de98e79bfb16f453050da47b1cdbdd551a5ac48 should install Vigem Properly then
