### ISSUE TITLE
PS3 controller

### ISSUE THREAD

**Issue by Korlon** [Alia5/GloSC#81]
Hello,
thank you for the great work.,
I have a strange setup (bound to the controllers lying around :-))

- Steam link with attached steam controller and a ps3 controller --> works like a charm with GloSC and Windows Store Games
- A PS3 Controller bound to the PC using SCP Toolkit to pose as XBOX Controller

Controller Rebinding is activated, but i get twice controller inputs. Since I do not really understand how exactly SCP and GloSC, resp. VIGEm Busdriver works. I guess the Input is really doubled. Once with the VIGem and once with SCP. Without SCP the PS3 Controller is not recognized.
Edit: Switched to shibari/fireshock - same behavior. (although working in general)

Is there any possibility how this can be solved in the meanwhile?

Best regards!

**Comment by IvanMoReau** [comment]
Don't use SCP/Shibari/Fireshock, just install the DS3 drivers from Playstation Now and it will be fine with Steam.

**Comment by Korlon** [comment]
oO, thank you for the reply - I didn't know that a driver for DS3 is shipped with PSNow. Thanks!

**Comment by Korlon** [comment]
Hi,
I disabled and removed the Shibari Service, uninstalled Fireshock and installed PSNow and it worked! Thank you very much!

**Comment by Korlon** [comment]
Hi!
Is it correct, that directly starting microsoft games from microsoft store will not work then with the ps3 controller? I have to use glosc and start the game via steam?

Best regards!

**Comment by Alia5** [comment]
Won't really be fixed until next version of HidGuardian is released. (and I manage to get my lazy ass working on GloSC)

**Comment by Korlon** [comment]
Apologies, I missed your answer - which is a good sign - I am completely happy with this solution. Thank you for your good work!
