### ISSUE TITLE
Game Starts with Different Problems Each Time (v2.0.5)

### ISSUE THREAD

**Issue by VoxsoldDragon** [Alia5/GloSC#82]
Just started using GloSC today, I had some initial issues with getting the Virtual Gamepad Emulation Bus to download. I got all that resolved with a separate install, but now I am experiencing a different issue. 

The problem occurs when I run Minecraft UWP with overlay enabled, virtual controllers enables, and the Launch Game and Close Shortcut options selected. I'm using Windows 10 64bit and a Nintendo Switch controller with everything updated, let me know if I need to provide more info.

When I launch Minecraft from BPM in steam or on steam link, the first time the Overlay loads to a blank screen. I am able to hit the steam button and close the shortcut. If I launch the Minecraft shortcut a second time the game pops up like it has been running the entire time, the game controls will work but the overlay will not open (I can hear it in the background if I hit the steam navigation button). If I launch the Minecraft shortcut a thrid time the game launches normally, but the overlay and controls are all disabled. I tried a fourth time for experimentation sake, the shortcut crashes every subsequent time.

The only way to break this cycle is to completely exit out of steam. This is happening with my Nintendo Switch controller and the Steam Controller. 

An interesting note. if I launch the shortcut in regular desktop mode, the GloSC loads but not the game. If I hit the play button again the game opens then crashes, but several GloSC windows are left open.

Let me know if you have a solution, I didn't see anyone else experiencing this.

**Comment by mydevice007** [comment]
Exactly the same issue here.

**Comment by Alia5** [comment]
Github is not a helpdesk
