### ISSUE TITLE
GloSC does not recognize Halo Master Chief Collection UWP

### ISSUE THREAD

**Issue by googlematt** [Alia5/GloSC#96]
Does not recognize Halo Master Chief Collection UWP.  Does not show up in list.

Have to manually enter the UWP path, and even then it won't launch from Steam

**Comment by Thracky** [comment]
This was solved with pull request #89 but a new build hasn’t been created in the main project yet so I went and built one myself.

It’s available at https://github.com/Thracky/GloSC/releases/tag/2.0.7

**Comment by Thracky** [comment]
Resolved in #89 and new build is available on my fork and will be available here soon.
